'use client';
import {useEffect,useState} from 'react';
import {Bell,Plus,CheckCircle2,Trash2,RefreshCw,AlertTriangle} from 'lucide-react';
type Rule={id:string;name:string;deviceId:string;streamId:string;operator:string;threshold:number;severity:string;cooldownSeconds:number;enabled:boolean;active:boolean;action:string;webhookUrl:string};
type Delivery={id:string;eventId:string;url:string;status:string;statusCode:number|null;error:string|null;timestamp:string};
type Event={id:string;ruleName:string;deviceId:string;streamId:string;value:number;threshold:number;operator:string;severity:string;message:string;timestamp:string;acknowledged:boolean};
const sev=(s:string)=>s==='critical'?'alertCritical':s==='warning'?'alertWarning':'alertInfo';
export default function AlertsPanel(){
 const [rules,setRules]=useState<Rule[]>([]),[events,setEvents]=useState<Event[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [draft,setDraft]=useState({name:'',deviceId:'demo-device',streamId:'temperature',operator:'>',threshold:'35',severity:'warning',cooldownSeconds:'300',action:'none',webhookUrl:''});
 async function load(){setLoading(true);setError('');try{const [a,b,c]=await Promise.all([fetch('/api/v1/alerts/rules',{cache:'no-store'}),fetch('/api/v1/alerts/events',{cache:'no-store'}),fetch('/api/v1/alerts/deliveries',{cache:'no-store'})]);const aj=await a.json(),bj=await b.json(),cj=await c.json();if(!a.ok)throw Error(aj.error);setRules(aj.rules||[]);setEvents(bj.events||[]);setDeliveries(cj.deliveries||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load alerts')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(){if(!draft.name||!draft.deviceId||!draft.streamId)return setError('Enter a rule name, device ID and stream ID.');const r=await fetch('/api/v1/alerts/rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,threshold:Number(draft.threshold),cooldownSeconds:Number(draft.cooldownSeconds),action:draft.action,webhookUrl:draft.webhookUrl})});const j=await r.json();if(!r.ok)return setError(j.error||'Unable to create rule');setDraft({...draft,name:''});load()}
 async function toggle(rule:Rule){await fetch('/api/v1/alerts/rules',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:rule.id,enabled:!rule.enabled})});load()}
 async function remove(id:string){await fetch(`/api/v1/alerts/rules?id=${encodeURIComponent(id)}`,{method:'DELETE'});load()}
 async function ack(id:string){await fetch(`/api/v1/alerts/events/${id}/ack`,{method:'POST'});load()}
 return <div className="alertsPage"><div className="hero"><div><span className="eyebrow">TELEMETRY</span><h1>Alerts</h1><p>Turn live telemetry into threshold events with cooldowns and acknowledgement.</p></div><div className="heroActions"><span className="alertCount"><Bell size={14}/>{events.filter(e=>!e.acknowledged).length} active</span><button className="secondary" onClick={load}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh'}</button></div></div>
 {error&&<div className="fleetError">{error}</div>}
 <div className="stats"><Stat label="Rules" value={rules.length}/><Stat label="Enabled" value={rules.filter(r=>r.enabled).length}/><Stat label="Active" value={rules.filter(r=>r.active).length}/><Stat label="Events" value={events.length}/></div>
 <div className="alertsGrid"><div className="panel"><div className="sectionHead"><div><h2>Create alert rule</h2><span>Numeric telemetry thresholds are evaluated at ingestion.</span></div></div><div className="premiumForm alertForm"><label>Name<input className="premiumField" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Temperature too high"/></label><label>Device ID<input className="premiumField" value={draft.deviceId} onChange={e=>setDraft({...draft,deviceId:e.target.value})}/></label><label>Stream ID<input className="premiumField" value={draft.streamId} onChange={e=>setDraft({...draft,streamId:e.target.value})}/></label><label>Condition<select className="premiumField" value={draft.operator} onChange={e=>setDraft({...draft,operator:e.target.value})}><option>&gt;</option><option>&gt;=</option><option>&lt;</option><option>&lt;=</option><option>=</option><option>!=</option></select></label><label>Threshold<input className="premiumField" type="number" value={draft.threshold} onChange={e=>setDraft({...draft,threshold:e.target.value})}/></label><label>Severity<select className="premiumField" value={draft.severity} onChange={e=>setDraft({...draft,severity:e.target.value})}><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label><label>Cooldown (sec)<input className="premiumField" type="number" min="0" value={draft.cooldownSeconds} onChange={e=>setDraft({...draft,cooldownSeconds:e.target.value})}/></label><label>Action<select className="premiumField" value={draft.action} onChange={e=>setDraft({...draft,action:e.target.value})}><option value="none">Create event only</option><option value="webhook">POST webhook</option></select></label>{draft.action==='webhook'&&<label className="webhookField">Webhook URL<input className="premiumField" value={draft.webhookUrl} onChange={e=>setDraft({...draft,webhookUrl:e.target.value})} placeholder="https://example.com/sylvia"/></label>}<div className="alertCreate"><button className="primary" onClick={create}><Plus size={14}/> Create rule</button></div></div></div>
 <div className="panel"><div className="sectionHead"><div><h2>Rules</h2><span>Cooldown prevents repeated events while a condition remains true.</span></div></div><div className="alertList">{rules.map(r=><div className="alertRule" key={r.id}><div className={`alertIcon ${sev(r.severity)}`}>{r.active?<AlertTriangle size={16}/>:<Bell size={16}/>}</div><div className="alertMain"><b>{r.name}</b><span>{r.deviceId} · {r.streamId} · {r.operator} {r.threshold} · {r.cooldownSeconds}s cooldown</span></div><span className={`alertBadge ${r.enabled?'enabled':'disabled'}`}>{r.active?'TRIGGERED':r.enabled?'ENABLED':'PAUSED'}</span><button className="mini" onClick={()=>toggle(r)}>{r.enabled?'Pause':'Enable'}</button>{r.action==='webhook'&&<button className="mini" onClick={async()=>{await fetch('/api/v1/alerts/rules/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id})});load()}}>Test hook</button>}<button className="trash" onClick={()=>remove(r.id)}><Trash2 size={14}/></button></div>)}</div></div></div>
 <div className="panel"><div className="sectionHead"><div><h2>Recent alert events</h2><span>Events are generated directly by telemetry ingestion.</span></div></div>{events.length?<div className="alertEvents">{events.map(e=><div className={`alertEvent ${sev(e.severity)}`} key={e.id}><div><b>{e.ruleName}</b><span>{e.message} · {new Date(e.timestamp).toLocaleString()}</span></div><div className="alertEventAction">{e.acknowledged?<span className="ack"><CheckCircle2 size={14}/> Acknowledged</span>:<button className="secondary" onClick={()=>ack(e.id)}><CheckCircle2 size={14}/> Acknowledge</button>}</div></div>)}</div>:<div className="dashboardEmpty"><b>No alert events yet</b><span>Send a telemetry value that crosses a configured threshold to generate an event.</span></div>}</div><div className="panel"><div className="sectionHead"><div><h2>Webhook delivery</h2><span>Recent outbound alert deliveries and failures.</span></div></div>{deliveries.length?<div className="alertEvents">{deliveries.map(d=><div className="alertEvent" key={d.id}><div><b>{d.status==='sent'?'Delivered':'Delivery failed'}</b><span>{d.url} · {d.statusCode??'—'} · {d.error||new Date(d.timestamp).toLocaleString()}</span></div><span className={`alertBadge ${d.status==='sent'?'enabled':'disabled'}`}>{d.status.toUpperCase()}</span></div>)}</div>:<div className="dashboardEmpty"><b>No webhook deliveries</b><span>Configure a webhook action on an alert rule to send outbound events.</span></div>}</div>
 </div>
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
