'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,Bell,CheckCircle2,Clock3,Filter,RefreshCw,Webhook,XCircle} from 'lucide-react';

type EventItem={id:string;kind:'alert'|'delivery';severity:'info'|'warning'|'critical'|'success'|'error';title:string;message:string;deviceId:string;streamId:string;timestamp:string;acknowledged?:boolean;status?:string;statusCode?:number|null};
const severityIcon=(s:EventItem['severity'])=>s==='critical'||s==='error'?<XCircle size={16}/>:s==='warning'?<AlertTriangle size={16}/>:s==='success'?<CheckCircle2 size={16}/>:<Bell size={16}/>;
export default function EventCenter(){
 const [events,setEvents]=useState<EventItem[]>([]),[filter,setFilter]=useState('all'),[severity,setSeverity]=useState('all'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,d]=await Promise.all([fetch('/api/v1/alerts/events?limit=200',{cache:'no-store'}),fetch('/api/v1/alerts/deliveries?limit=200',{cache:'no-store'})]);const aj=await a.json(),dj=await d.json();if(!a.ok)throw Error(aj.error||'Unable to load events');const alerts=(aj.events||[]).map((e:any):EventItem=>({id:`alert:${e.id}`,kind:'alert',severity:e.severity,title:e.ruleName,message:e.message,deviceId:String(e.deviceId),streamId:String(e.streamId),timestamp:e.timestamp,acknowledged:e.acknowledged}));const deliveries=(dj.deliveries||[]).map((d:any):EventItem=>({id:`delivery:${d.id}`,kind:'delivery',severity:d.status==='sent'?'success':'error',title:'Webhook delivery',message:d.error||`${d.url} responded successfully`,deviceId:'—',streamId:'—',timestamp:d.timestamp,status:d.status,statusCode:d.statusCode}));setEvents([...alerts,...deliveries].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)))}catch(e){setError(e instanceof Error?e.message:'Event Center unavailable')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);
 const filtered=useMemo(()=>events.filter(e=>(filter==='all'||e.kind===filter)&&(severity==='all'||e.severity===severity)),[events,filter,severity]);
 const active=events.filter(e=>e.kind==='alert'&&!e.acknowledged).length, alerts=events.filter(e=>e.kind==='alert').length, deliveries=events.filter(e=>e.kind==='delivery').length, failed=events.filter(e=>e.kind==='delivery'&&e.status==='failed').length;
 return <div className="eventCenter"><div className="hero"><div><span className="eyebrow">EVENT CENTER</span><h1>One timeline for what SYLVIA sees.</h1><p>Review telemetry alerts and webhook delivery activity in one place. The feed refreshes automatically.</p></div><div className="heroActions"><span className="eventLive"><i/>Live · 5s</span><button className="secondary" onClick={load}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh'}</button></div></div>
  <div className="eventStats"><div><strong>{active}</strong><span>Active alerts</span></div><div><strong>{alerts}</strong><span>Alert events</span></div><div><strong>{deliveries}</strong><span>Webhook deliveries</span></div><div><strong>{failed}</strong><span>Failed deliveries</span></div></div>
  <div className="eventToolbar"><div className="filterLabel"><Filter size={14}/><b>Filter</b></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All events</option><option value="alert">Alerts</option><option value="delivery">Webhook deliveries</option></select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severity</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option><option value="success">Success</option><option value="error">Error</option></select></div>
  {error&&<div className="eventError">{error}</div>}
  <div className="panel eventPanel"><div className="sectionHead"><div><h2>Event timeline</h2><span>{filtered.length} matching events · newest first</span></div><span className="eventSync"><Activity size={14}/> Auto-synced</span></div>{filtered.length===0?<div className="eventEmpty"><Bell size={24}/><b>No matching events</b><span>Telemetry alerts and webhook activity will appear here as they occur.</span></div>:<div className="eventTimeline">{filtered.map(e=><article className={`eventItem ${e.severity}`} key={e.id}><div className="eventIcon">{severityIcon(e.severity)}</div><div className="eventBody"><div className="eventTop"><b>{e.title}</b><time>{new Date(e.timestamp).toLocaleString()}</time></div><p>{e.message}</p><div className="eventMeta"><span>{e.kind==='alert'?'Alert':'Webhook'}</span><span>Device {e.deviceId}</span><span>{e.streamId!=='—'?`Stream ${e.streamId}`:'Delivery'}</span>{e.status&&<span>{e.status}{e.statusCode?` · HTTP ${e.statusCode}`:''}</span>}{e.acknowledged&&<span className="ack"><CheckCircle2 size={12}/> Acknowledged</span>}</div></div></article>)}</div>}</div>
  <div className="eventFooter"><Clock3 size={14}/> Event history is currently an in-memory beta store; durable event retention is planned for a later release.</div>
 </div>;
}
