'use client';
import {useCallback,useEffect,useState} from 'react';
import {Bell,Plus,Trash2,RefreshCw,Users} from 'lucide-react';
type Sub={id:string;userId:string;projectId:string;kind:'all'|'alert'|'delivery';severity:'all'|'info'|'warning'|'critical'|'success'|'error';enabled:boolean};
export default function NotificationSubscriptions(){const [items,setItems]=useState<Sub[]>([]),[kind,setKind]=useState<Sub['kind']>('all'),[severity,setSeverity]=useState<Sub['severity']>('all'),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/v1/notifications/subscriptions?projectId=sylvia-local-workspace&userId=usr_owner',{cache:'no-store'});const j=await r.json();setItems(j.subscriptions||[])}catch{setMsg('Subscription API unavailable')}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const add=async()=>{const r=await fetch('/api/v1/notifications/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,severity})});const j=await r.json();if(r.ok){setMsg('Subscription added');load()}else setMsg(j.error||'Unable to add subscription')};
 const toggle=async(s:Sub)=>{await fetch('/api/v1/notifications/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,enabled:!s.enabled})});load()};
 const remove=async(id:string)=>{await fetch(`/api/v1/notifications/subscriptions?id=${encodeURIComponent(id)}`,{method:'DELETE'});load()};
 return <div className="subscriptionPanel panel"><div className="sectionHead"><div><h2><Users size={16}/> Event subscriptions</h2><span>Route only the notification types and severities this project needs.</span></div><button className="secondary" onClick={load}><RefreshCw size={13}/>{loading?'Loading…':'Refresh'}</button></div><div className="subscriptionCreate"><select value={kind} onChange={e=>setKind(e.target.value as Sub['kind'])}><option value="all">All event types</option><option value="alert">Telemetry alerts</option><option value="delivery">Webhook deliveries</option></select><select value={severity} onChange={e=>setSeverity(e.target.value as Sub['severity'])}><option value="all">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option><option value="success">Success</option><option value="error">Error</option></select><button className="primary" onClick={add}><Plus size={14}/> Add subscription</button></div>{msg&&<div className="subscriptionMsg">{msg}</div>}<div className="subscriptionList">{items.map(s=><div className="subscriptionRow" key={s.id}><div className="subscriptionIcon"><Bell size={15}/></div><div className="subscriptionMain"><b>{s.kind==='all'?'All events':s.kind==='alert'?'Telemetry alerts':'Webhook deliveries'}</b><span>{s.severity==='all'?'Any severity':s.severity} · Project <code>{s.projectId}</code> · User <code>{s.userId}</code></span></div><span className={s.enabled?'enabled':'disabled'}>{s.enabled?'Active':'Paused'}</span><button className="mini" onClick={()=>toggle(s)}>{s.enabled?'Pause':'Enable'}</button>{s.id!=='sub_default'&&<button className="trash" onClick={()=>remove(s.id)} aria-label="Delete subscription"><Trash2 size={14}/></button>}</div>)}{!items.length&&<div className="emptyMini">No subscriptions configured.</div>}</div></div>}
