'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Bell,Check,CheckCheck,RefreshCw,SlidersHorizontal,AlertTriangle,XCircle,CheckCircle2,Webhook} from 'lucide-react';

type Notification={id:string;kind:'alert'|'delivery'|'system';severity:'info'|'warning'|'critical'|'success'|'error';title:string;message:string;timestamp:string;read:boolean;deviceId?:string;streamId?:string};
type Preferences={inApp:boolean;alertNotifications:boolean;webhookNotifications:boolean;criticalOnly:boolean};
const icon=(s:Notification['severity'])=>s==='critical'||s==='error'?<XCircle size={17}/>:s==='warning'?<AlertTriangle size={17}/>:s==='success'?<CheckCircle2 size={17}/>:<Bell size={17}/>;
const cls=(s:string)=>s==='critical'||s==='error'?'notificationCritical':s==='warning'?'notificationWarning':s==='success'?'notificationSuccess':'notificationInfo';
export default function NotificationCenter(){
 const [items,setItems]=useState<Notification[]>([]),[prefs,setPrefs]=useState<Preferences>({inApp:true,alertNotifications:true,webhookNotifications:true,criticalOnly:false}),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [n,p]=await Promise.all([fetch('/api/v1/notifications?limit=200',{cache:'no-store'}),fetch('/api/v1/notifications/preferences',{cache:'no-store'})]);const nj=await n.json(),pj=await p.json();if(!n.ok)throw Error(nj.error||'Unable to load notifications');setItems(nj.notifications||[]);if(p.ok)setPrefs(pj.preferences)}catch(e){setError(e instanceof Error?e.message:'Notification Center unavailable')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load]);
 const filtered=useMemo(()=>items.filter(n=>filter==='all'||(filter==='unread'&&!n.read)||n.severity===filter),[items,filter]);
 const unread=items.filter(n=>!n.read).length;
 async function read(id:string){await fetch(`/api/v1/notifications/${encodeURIComponent(id)}/read`,{method:'POST'});setItems(xs=>xs.map(n=>n.id===id?{...n,read:true}:n));}
 async function readAll(){await fetch('/api/v1/notifications/read-all',{method:'POST'});setItems(xs=>xs.map(n=>({...n,read:true})));}
 async function savePrefs(patch:Partial<Preferences>){const next={...prefs,...patch};setPrefs(next);await fetch('/api/v1/notifications/preferences',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});}
 return <div className="notificationCenter"><div className="hero"><div><span className="eyebrow">NOTIFICATION CENTER</span><h1>Important events, without the noise.</h1><p>Keep alert and delivery activity in one in-app inbox. Read state and notification preferences are ready for future email and push channels.</p></div><div className="heroActions"><span className="notificationUnread"><Bell size={14}/>{unread} unread</span><button className="secondary" onClick={load}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh'}</button></div></div>
 {error&&<div className="fleetError">{error}</div>}
 <div className="stats"><Stat label="Notifications" value={items.length}/><Stat label="Unread" value={unread}/><Stat label="Alerts" value={items.filter(n=>n.kind==='alert').length}/><Stat label="Deliveries" value={items.filter(n=>n.kind==='delivery').length}/></div>
 <div className="notificationGrid"><div className="panel"><div className="sectionHead"><div><h2>Inbox</h2><span>Newest activity appears automatically.</span></div><button className="secondary" onClick={readAll} disabled={!unread}><CheckCheck size={14}/> Mark all read</button></div><div className="notificationToolbar"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='unread'?'selected':''} onClick={()=>setFilter('unread')}>Unread</button><button className={filter==='critical'?'selected':''} onClick={()=>setFilter('critical')}>Critical</button><button className={filter==='warning'?'selected':''} onClick={()=>setFilter('warning')}>Warning</button></div><div className="notificationList">{filtered.length?filtered.map(n=><div className={`notificationItem ${cls(n.severity)} ${n.read?'read':'unread'}`} key={n.id}><div className="notificationIcon">{icon(n.severity)}</div><div className="notificationBody"><div className="notificationTop"><b>{n.title}</b><time>{new Date(n.timestamp).toLocaleString()}</time></div><p>{n.message}</p><div className="notificationMeta">{n.kind==='alert'?<span><Bell size={10}/> Alert</span>:<span><Webhook size={10}/> Webhook</span>}{n.deviceId&&<span>{n.deviceId}</span>}{n.streamId&&<span>{n.streamId}</span>}{!n.read&&<span className="notificationNew">NEW</span>}</div></div>{!n.read&&<button className="mini" onClick={()=>read(n.id)} title="Mark as read"><Check size={13}/></button>}</div>):<div className="notificationEmpty"><Bell size={24}/><b>No notifications</b><span>New alert events and webhook results will appear here.</span></div>}</div></div>
 <div className="panel"><div className="sectionHead"><div><h2><SlidersHorizontal size={16}/> Preferences</h2><span>Choose which events appear in the in-app inbox.</span></div></div><div className="notificationPrefs"><Toggle label="In-app notifications" hint="Show activity in this inbox" value={prefs.inApp} onChange={v=>savePrefs({inApp:v})}/><Toggle label="Alert notifications" hint="Telemetry threshold events" value={prefs.alertNotifications} onChange={v=>savePrefs({alertNotifications:v})}/><Toggle label="Webhook notifications" hint="Delivery success and failures" value={prefs.webhookNotifications} onChange={v=>savePrefs({webhookNotifications:v})}/><Toggle label="Critical only" hint="Hide info, warning and successful delivery items" value={prefs.criticalOnly} onChange={v=>savePrefs({criticalOnly:v})}/></div><div className="notificationFuture"><b>Future channels</b><span>Email and mobile push are intentionally reserved for a later beta so SYLVIA stays dependency-light.</span></div></div></div></div>
}
function Toggle({label,hint,value,onChange}:{label:string;hint:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="notificationToggle"><span><b>{label}</b><small>{hint}</small></span><button type="button" className={value?'switch on':'switch'} onClick={()=>onChange(!value)} aria-label={label}><i/></button></label>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
