'use client';
import { useEffect, useState } from 'react';
import { BellRing, Mail, Radio, Send, Trash2, Webhook } from 'lucide-react';

type Provider={id:string;name:string;kind:'webhook'|'email-http'|'push-http'|'console';enabled:boolean;endpoint?:string;from?:string;createdAt:string};
type Delivery={id:string;providerId:string;kind:string;status:'sent'|'failed';statusCode:number|null;error:string|null;timestamp:string};
const labels={webhook:'Webhook', 'email-http':'Email HTTP adapter','push-http':'Push HTTP adapter',console:'Local console'};
export default function NotificationProviders(){
 const [providers,setProviders]=useState<Provider[]>([]); const [deliveries,setDeliveries]=useState<Delivery[]>([]); const [busy,setBusy]=useState(false); const [form,setForm]=useState({name:'',kind:'webhook' as Provider['kind'],endpoint:'',from:''});
 async function load(){const [p,d]=await Promise.all([fetch('/api/v1/notifications/providers'),fetch('/api/v1/notifications/providers?deliveries=1')]);setProviders((await p.json()).providers||[]);setDeliveries((await d.json()).deliveries||[])}
 useEffect(()=>{void load()},[]);
 async function add(){setBusy(true);await fetch('/api/v1/notifications/providers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});setForm({name:'',kind:'webhook',endpoint:'',from:''});await load();setBusy(false)}
 async function test(id:string){await fetch('/api/v1/notifications/providers/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerId:id})});await load()}
 async function remove(id:string){await fetch(`/api/v1/notifications/providers?id=${encodeURIComponent(id)}`,{method:'DELETE'});await load()}
 return <div className="apiPage"><div className="hero"><div><span className="eyebrow">NOTIFICATION DELIVERY</span><h1>Providers, ready for email and push.</h1><p>Configure optional delivery adapters without coupling the SYLVIA core to a single vendor.</p></div><div className="heroActions"><span className="enabled">Provider layer ready</span></div></div>
 <div className="stats"><Stat label="Providers" value={String(providers.length)}/><Stat label="Enabled" value={String(providers.filter(p=>p.enabled).length)}/><Stat label="Deliveries" value={String(deliveries.length)}/><Stat label="Failed" value={String(deliveries.filter(d=>d.status==='failed').length)}/></div>
 <div className="panel"><div className="sectionHead"><div><h2>Add provider</h2><span>Email and push adapters use a generic HTTP contract in beta.</span></div></div><div className="settingsGrid"><label>Name<input className="premiumField" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="My email provider"/></label><label>Type<select className="premiumField" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as Provider['kind']})}><option value="webhook">Webhook</option><option value="email-http">Email HTTP adapter</option><option value="push-http">Push HTTP adapter</option><option value="console">Local console</option></select></label>{form.kind!=='console'&&<label>Endpoint<input className="premiumField" value={form.endpoint} onChange={e=>setForm({...form,endpoint:e.target.value})} placeholder="https://provider.example/send"/></label>}{form.kind==='email-http'&&<label>From<input className="premiumField" value={form.from} onChange={e=>setForm({...form,from:e.target.value})} placeholder="alerts@example.com"/></label>}</div><button className="primary" disabled={busy||!form.name} onClick={add}><PlusIcon/>{busy?'Adding…':'Add provider'}</button></div>
 <div className="apiGrid"><div className="panel"><div className="sectionHead"><div><h2>Configured providers</h2><span>Provider credentials should be supplied through your hosted secret manager.</span></div></div>{providers.map(p=><div className="keyRow" key={p.id}><div className="apiTitle">{p.kind==='email-http'?<Mail size={17}/>:p.kind==='push-http'?<Radio size={17}/>:p.kind==='webhook'?<Webhook size={17}/>:<BellRing size={17}/>}<div><b>{p.name}</b><small>{labels[p.kind]}{p.endpoint?` · ${p.endpoint}`:''}</small></div></div><div className="heroActions"><button className="mini" onClick={()=>test(p.id)}><Send size={13}/> Test</button>{p.id!=='provider-console'&&<button className="trash" onClick={()=>remove(p.id)}><Trash2 size={15}/></button>}</div></div>)}</div><div className="panel"><div className="sectionHead"><div><h2>Delivery history</h2><span>Last 100 beta delivery attempts.</span></div></div>{deliveries.slice(0,12).map(d=><div className="endpoint" key={d.id}><span className="endpointDot"/><div><b>{d.status==='sent'?'Delivered':'Failed'} · {d.kind}</b><small>{d.error||`HTTP ${d.statusCode??'n/a'}`} · {new Date(d.timestamp).toLocaleString()}</small></div></div>)}</div></div></div>
}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><span>{label}</span><b>{value}</b></div>}
function PlusIcon(){return <span>＋</span>}
