import { databaseConfigured, query } from "@/lib/db";
import { createPersistentCommand, generatePersistentCommandId, markPersistentCommandSent, requeuePersistentCommand } from "@/lib/persistent-commands";
import { publishDeviceCommand, mqttStatus } from "@/lib/mqtt-transport";
import { recordDeviceEvent } from "@/lib/device-events";

export type AutomationOperator = '>' | '>=' | '<' | '<=' | '=' | '!=';
export type AutomationAction = 'device_command' | 'event';
export type AutomationRule = { id:string; ownerId:string; projectId:string; name:string; deviceId:string; streamId:string; operator:AutomationOperator; threshold:number; action:AutomationAction; command:string|null; payload:unknown; cooldownSeconds:number; enabled:boolean; lastTriggeredAt:string|null; createdAt:string; updatedAt:string };
export type Schedule = { id:string; ownerId:string; projectId:string; name:string; deviceId:string; command:string; payload:unknown; hour:number; minute:number; daysOfWeek:number[]; timezone:string; enabled:boolean; lastRunAt:string|null; createdAt:string; updatedAt:string };
function normalizeRule(row:Record<string,unknown>):AutomationRule{return{id:String(row.id),ownerId:String(row.owner_id),projectId:String(row.project_id),name:String(row.name),deviceId:String(row.device_id),streamId:String(row.stream_id),operator:row.operator as AutomationOperator,threshold:Number(row.threshold),action:row.action as AutomationAction,command:row.command?String(row.command):null,payload:row.payload??{},cooldownSeconds:Number(row.cooldown_seconds??300),enabled:Boolean(row.enabled),lastTriggeredAt:row.last_triggered_at?new Date(String(row.last_triggered_at)).toISOString():null,createdAt:new Date(String(row.created_at)).toISOString(),updatedAt:new Date(String(row.updated_at)).toISOString()};}
function normalizeSchedule(row:Record<string,unknown>):Schedule{return{id:String(row.id),ownerId:String(row.owner_id),projectId:String(row.project_id),name:String(row.name),deviceId:String(row.device_id),command:String(row.command),payload:row.payload??{},hour:Number(row.hour),minute:Number(row.minute),daysOfWeek:Array.isArray(row.days_of_week)?row.days_of_week.map(Number):[0,1,2,3,4,5,6],timezone:String(row.timezone||'Asia/Kolkata'),enabled:Boolean(row.enabled),lastRunAt:row.last_run_at?new Date(String(row.last_run_at)).toISOString():null,createdAt:new Date(String(row.created_at)).toISOString(),updatedAt:new Date(String(row.updated_at)).toISOString()};}
function compare(value:number,operator:AutomationOperator,threshold:number){return operator==='>'?value>threshold:operator==='>='?value>=threshold:operator==='<'?value<threshold:operator==='<='?value<=threshold:operator==='='?value===threshold:value!==threshold;}

export async function listAutomationRules(ownerId:string){if(!databaseConfigured())return[];try{const r=await query(`SELECT id,owner_id,project_id,name,device_id,stream_id,operator,threshold,action,command,payload,cooldown_seconds,enabled,last_triggered_at,created_at,updated_at FROM public.automation_rules WHERE owner_id=$1 ORDER BY name ASC`,[ownerId]);return r.rows.map(x=>normalizeRule(x as Record<string,unknown>));}catch{return[];}}
export async function createAutomationRule(input:{ownerId:string;projectId?:string;name:string;deviceId:string;streamId:string;operator:AutomationOperator;threshold:number;action:AutomationAction;command?:string|null;payload?:unknown;cooldownSeconds?:number;enabled?:boolean}){if(!databaseConfigured())return null;const owned=await query("SELECT 1 FROM public.device_registry WHERE device_id=$1 AND owner_id=$2 LIMIT 1",[String(input.deviceId),input.ownerId]);if(!owned.rows[0])throw new Error("Device not found in this workspace");const stream=await query("SELECT 1 FROM public.datastream_registry WHERE datastream_id=$1 AND device_id=$2 LIMIT 1",[String(input.streamId),String(input.deviceId)]);if(!stream.rows[0])throw new Error("Datastream does not belong to the selected device");const id=`auto_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;const r=await query(`INSERT INTO public.automation_rules (id,owner_id,project_id,name,device_id,stream_id,operator,threshold,action,command,payload,cooldown_seconds,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13) RETURNING id,owner_id,project_id,name,device_id,stream_id,operator,threshold,action,command,payload,cooldown_seconds,enabled,last_triggered_at,created_at,updated_at`,[id,input.ownerId,input.projectId||'sylvia-local-workspace',input.name.trim(),String(input.deviceId),String(input.streamId),input.operator,input.threshold,input.action,input.command?.trim()||null,JSON.stringify(input.payload??{}),Math.max(0,Math.min(Math.trunc(input.cooldownSeconds??300),86400)),input.enabled!==false]);return normalizeRule(r.rows[0] as Record<string,unknown>);}
export async function updateAutomationRule(id:string,ownerId:string,patch:Partial<Pick<AutomationRule,'name'|'operator'|'threshold'|'action'|'command'|'payload'|'cooldownSeconds'|'enabled'>>){if(!databaseConfigured())return null;const allowed:Record<string,string>={name:'name',operator:'operator',threshold:'threshold',action:'action',command:'command',payload:'payload',cooldownSeconds:'cooldown_seconds',enabled:'enabled'};const entries=Object.entries(patch).filter(([k,v])=>k in allowed&&v!==undefined);if(!entries.length)return null;const sets:string[]=[];const values:unknown[]=[id,ownerId];for(const [k,v] of entries){values.push(k==='payload'?JSON.stringify(v):k==='cooldownSeconds'?Math.max(0,Math.min(Math.trunc(Number(v)),86400)):v);sets.push(`${allowed[k]}=$${values.length}${k==='payload'?'::jsonb':''}`);}values.push(new Date().toISOString());const r=await query(`UPDATE public.automation_rules SET ${sets.join(',')},updated_at=$${values.length} WHERE id=$1 AND owner_id=$2 RETURNING id,owner_id,project_id,name,device_id,stream_id,operator,threshold,action,command,payload,cooldown_seconds,enabled,last_triggered_at,created_at,updated_at`,values);return r.rows[0]?normalizeRule(r.rows[0] as Record<string,unknown>):null;}
export async function deleteAutomationRule(id:string,ownerId:string){if(!databaseConfigured())return false;const r=await query(`DELETE FROM public.automation_rules WHERE id=$1 AND owner_id=$2`,[id,ownerId]);return r.rowCount===1;}

async function dispatchCommand(ownerId:string,deviceId:string,command:string,payload:unknown){const owned=await query("SELECT 1 FROM public.device_registry WHERE device_id=$1 AND owner_id=$2 LIMIT 1",[String(deviceId),ownerId]);if(!owned.rows[0])throw new Error("Device not found in this workspace");const commandId=generatePersistentCommandId();const persisted=await createPersistentCommand(commandId,deviceId,command,payload);if(!persisted)throw new Error('Persistent command could not be created');if(mqttStatus().configured){try{const sent=await markPersistentCommandSent(commandId);if(!sent)throw new Error('Persistent command could not be marked sent');await publishDeviceCommand(deviceId,{commandId,command,payload,timestamp:new Date().toISOString()});return{commandId,status:'dispatched' as const};}catch(error){await requeuePersistentCommand(commandId);return{commandId,status:'queued' as const,error:error instanceof Error?error.message:'MQTT dispatch failed'};}}return{commandId,status:'queued' as const};}
async function createRun(input:{ownerId:string;sourceType:'rule'|'schedule';sourceId:string;deviceId:string;triggerValue?:number|null;action:string;status:'triggered'|'queued'|'dispatched'|'failed';commandId?:string|null;error?:string|null;executionKey?:string}){const id=`run_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;try{const r=await query(`INSERT INTO public.automation_runs (id,execution_key,owner_id,source_type,source_id,device_id,trigger_value,action,status,command_id,error) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (execution_key) DO NOTHING RETURNING id,execution_key,owner_id,source_type,source_id,device_id,trigger_value,action,status,command_id,error,created_at`,[id,input.executionKey||null,input.ownerId,input.sourceType,input.sourceId,input.deviceId,input.triggerValue??null,input.action,input.status,input.commandId??null,input.error??null]);return r.rows[0]||null;}catch{return null;}}

export async function evaluateAutomationTelemetry(deviceId:string,streamId:string,value:number){if(!databaseConfigured()||!Number.isFinite(value))return[];const rules=await query(`SELECT id,owner_id,project_id,name,device_id,stream_id,operator,threshold,action,command,payload,cooldown_seconds,enabled,last_triggered_at,created_at,updated_at FROM public.automation_rules WHERE device_id=$1 AND stream_id=$2 AND enabled=true ORDER BY created_at ASC`,[deviceId,streamId]);const results=[];for(const raw of rules.rows){const rule=normalizeRule(raw as Record<string,unknown>);if(!compare(value,rule.operator,rule.threshold))continue;const claim=await query(`UPDATE public.automation_rules SET last_triggered_at=now(),updated_at=now() WHERE id=$1 AND enabled=true AND (last_triggered_at IS NULL OR last_triggered_at <= now() - ($2::text || ' seconds')::interval) RETURNING id,owner_id,project_id,name,device_id,stream_id,operator,threshold,action,command,payload,cooldown_seconds,enabled,last_triggered_at,created_at,updated_at`,[rule.id,rule.cooldownSeconds]);if(!claim.rows[0])continue;const claimed=normalizeRule(claim.rows[0] as Record<string,unknown>);let status:'triggered'|'queued'|'dispatched'|'failed'='triggered';let commandId:string|null=null;let error:string|null=null;if(claimed.action==='device_command'){if(!claimed.command){status='failed';error='Automation command is missing';}else{try{const dispatched=await dispatchCommand(claimed.ownerId,deviceId,claimed.command,claimed.payload);commandId=dispatched.commandId;status=dispatched.status;error=dispatched.error||null;}catch(e){status='failed';error=e instanceof Error?e.message:'Automation command failed';}}}const run=await createRun({ownerId:claimed.ownerId,sourceType:'rule',sourceId:claimed.id,deviceId,triggerValue:value,action:claimed.action,status,commandId,error});await recordDeviceEvent({deviceId,ownerId:claimed.ownerId,kind:'automation.triggered',severity:status==='failed'?'warning':'info',message:`Automation ${claimed.name} triggered`,data:{automationId:claimed.id,value,status,commandId,error}});results.push({rule:claimed,run,status,commandId,error});}return results;}

export async function listAutomationRuns(ownerId:string,limit=100){if(!databaseConfigured())return[];const safe=Math.max(1,Math.min(Math.trunc(limit),200));try{const r=await query(`SELECT id,execution_key,owner_id,source_type,source_id,device_id,trigger_value,action,status,command_id,error,created_at FROM public.automation_runs WHERE owner_id=$1 ORDER BY created_at DESC LIMIT $2`,[ownerId,safe]);return r.rows;}catch{return[];}}
export async function listSchedules(ownerId:string){if(!databaseConfigured())return[];try{const r=await query(`SELECT id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled,last_run_at,created_at,updated_at FROM public.schedules WHERE owner_id=$1 ORDER BY hour ASC,minute ASC,name ASC`,[ownerId]);return r.rows.map(x=>normalizeSchedule(x as Record<string,unknown>));}catch{return[];}}
export async function createSchedule(input:{ownerId:string;projectId?:string;name:string;deviceId:string;command:string;payload?:unknown;hour:number;minute:number;daysOfWeek?:number[];timezone?:string;enabled?:boolean}){if(!databaseConfigured())return null;const owned=await query("SELECT 1 FROM public.device_registry WHERE device_id=$1 AND owner_id=$2 LIMIT 1",[String(input.deviceId),input.ownerId]);if(!owned.rows[0])throw new Error("Device not found in this workspace");const id=`sch_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;const days=(input.daysOfWeek?.length?input.daysOfWeek:[0,1,2,3,4,5,6]).filter(x=>Number.isInteger(x)&&x>=0&&x<=6);if(!days.length)throw new Error('At least one day is required');const r=await query(`INSERT INTO public.schedules (id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,$12) RETURNING id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled,last_run_at,created_at,updated_at`,[id,input.ownerId,input.projectId||'sylvia-local-workspace',input.name.trim(),String(input.deviceId),input.command.trim(),JSON.stringify(input.payload??{}),Math.max(0,Math.min(23,Math.trunc(input.hour))),Math.max(0,Math.min(59,Math.trunc(input.minute))),days,input.timezone||'Asia/Kolkata',input.enabled!==false]);return normalizeSchedule(r.rows[0] as Record<string,unknown>);}
export async function updateSchedule(id:string,ownerId:string,patch:Record<string,unknown>){if(!databaseConfigured())return null;const fieldMap:{[key:string]:string}={name:'name',command:'command',payload:'payload',hour:'hour',minute:'minute',daysOfWeek:'days_of_week',timezone:'timezone',enabled:'enabled',projectId:'project_id'};const entries=Object.entries(patch).filter(([k,v])=>fieldMap[k]&&v!==undefined);if(!entries.length)return null;const values:unknown[]=[id,ownerId];const sets:string[]=[];for(const [k,v] of entries){let value=v;if(k==='payload')value=JSON.stringify(v);if(k==='hour')value=Math.max(0,Math.min(23,Math.trunc(Number(v))));if(k==='minute')value=Math.max(0,Math.min(59,Math.trunc(Number(v))));if(k==='daysOfWeek')value=Array.isArray(v)?v.filter(x=>Number.isInteger(x)&&x>=0&&x<=6):[0,1,2,3,4,5,6];values.push(value);sets.push(`${fieldMap[k]}=$${values.length}${k==='payload'?'::jsonb':''}`);}values.push(new Date().toISOString());const r=await query(`UPDATE public.schedules SET ${sets.join(',')},updated_at=$${values.length} WHERE id=$1 AND owner_id=$2 RETURNING id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled,last_run_at,created_at,updated_at`,values);return r.rows[0]?normalizeSchedule(r.rows[0] as Record<string,unknown>):null;}
export async function deleteSchedule(id:string,ownerId:string){if(!databaseConfigured())return false;const r=await query(`DELETE FROM public.schedules WHERE id=$1 AND owner_id=$2`,[id,ownerId]);return r.rowCount===1;}
function localParts(date:Date,timezone:string){try{const parts=new Intl.DateTimeFormat('en-US',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const get=(type:string)=>parts.find(x=>x.type===type)?.value||'';const weekdays:{[key:string]:number}={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};return{year:get('year'),month:get('month'),day:get('day'),hour:Number(get('hour')),minute:Number(get('minute')),weekday:weekdays[get('weekday')]};}catch{return null;}}
async function executeSchedule(schedule:Schedule,now:Date,manual=false){
  const parts=localParts(now,schedule.timezone);
  if(!parts)return{status:'failed',error:'Invalid schedule timezone'};
  const currentMinutes=parts.hour*60+parts.minute;
  const scheduledMinutes=schedule.hour*60+schedule.minute;
  if(!manual&&(!schedule.enabled||!schedule.daysOfWeek.includes(parts.weekday)||currentMinutes<scheduledMinutes))return{status:'skipped'};
  const localDate=`${parts.year}-${parts.month}-${parts.day}`;
  const executionKey=`schedule:${schedule.id}:${localDate}`;
  if(!manual){
    const claim=await query(
      `UPDATE public.schedules
       SET last_run_at=now(),updated_at=now()
       WHERE id=$1 AND enabled=true
         AND (EXTRACT(DOW FROM now() AT TIME ZONE timezone)::int = ANY(days_of_week))
         AND (EXTRACT(HOUR FROM now() AT TIME ZONE timezone)::int*60 + EXTRACT(MINUTE FROM now() AT TIME ZONE timezone)::int >= hour*60 + minute)
         AND (last_run_at IS NULL OR (last_run_at AT TIME ZONE timezone)::date < (now() AT TIME ZONE timezone)::date)
       RETURNING id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled,last_run_at,created_at,updated_at`,
      [schedule.id],
    );
    if(!claim.rows[0])return{status:'duplicate'};
  }
  try{
    const dispatched=await dispatchCommand(schedule.ownerId,schedule.deviceId,schedule.command,schedule.payload);
    const run=await createRun({ownerId:schedule.ownerId,sourceType:'schedule',sourceId:schedule.id,deviceId:schedule.deviceId,action:schedule.command,status:dispatched.status,commandId:dispatched.commandId,error:dispatched.error||null,executionKey:manual?undefined:executionKey});
    await recordDeviceEvent({deviceId:schedule.deviceId,ownerId:schedule.ownerId,kind:'schedule.executed',severity:dispatched.status==='queued'?'info':'success',message:`Schedule ${schedule.name} executed`,data:{scheduleId:schedule.id,command:schedule.command,status:dispatched.status,commandId:dispatched.commandId,manual}});
    return{status:dispatched.status,commandId:dispatched.commandId,error:dispatched.error||null,run};
  }catch(error){
    const message=error instanceof Error?error.message:'Schedule execution failed';
    const run=await createRun({ownerId:schedule.ownerId,sourceType:'schedule',sourceId:schedule.id,deviceId:schedule.deviceId,action:schedule.command,status:'failed',error:message,executionKey:manual?undefined:executionKey});
    return{status:'failed',error:message,run};
  }
}
export async function runDueSchedules(now=new Date()){if(!databaseConfigured())return[];const r=await query(`SELECT id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled,last_run_at,created_at,updated_at FROM public.schedules WHERE enabled=true ORDER BY hour ASC,minute ASC`);const out=[];for(const raw of r.rows){out.push({schedule:normalizeSchedule(raw as Record<string,unknown>),result:await executeSchedule(normalizeSchedule(raw as Record<string,unknown>),now,false)});}return out;}
export async function runScheduleNow(id:string,ownerId:string){if(!databaseConfigured())return null;const r=await query(`SELECT id,owner_id,project_id,name,device_id,command,payload,hour,minute,days_of_week,timezone,enabled,last_run_at,created_at,updated_at FROM public.schedules WHERE id=$1 AND owner_id=$2 LIMIT 1`,[id,ownerId]);if(!r.rows[0])return null;return executeSchedule(normalizeSchedule(r.rows[0] as Record<string,unknown>),new Date(),true);}