export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      projects: { Row: { id:string; name:string; slug:string; created_at:string; updated_at:string }; Insert: { id?:string; name:string; slug:string; created_at?:string; updated_at?:string }; Update: Partial<Database['public']['Tables']['projects']['Insert']> };
      project_members: { Row: { id:string; project_id:string; user_id:string; role:string; created_at:string }; Insert: { id?:string; project_id:string; user_id:string; role:string; created_at?:string }; Update: Partial<Database['public']['Tables']['project_members']['Insert']> };
      devices: { Row: { id:string; project_id:string; name:string; device_key:string; token_hash:string|null; status:string; transport:string; firmware_version:string|null; last_seen_at:string|null; metadata:Json; created_at:string; updated_at:string }; Insert: { id?:string; project_id:string; name:string; device_key:string; token_hash?:string|null; status?:string; transport?:string; firmware_version?:string|null; last_seen_at?:string|null; metadata?:Json; created_at?:string; updated_at?:string }; Update: Partial<Database['public']['Tables']['devices']['Insert']> };
      datastreams: { Row: { id:string; device_id:string; name:string; key:string; data_type:string; unit:string|null; min_value:number|null; max_value:number|null; created_at:string }; Insert: { id?:string; device_id:string; name:string; key:string; data_type?:string; unit?:string|null; min_value?:number|null; max_value?:number|null; created_at?:string }; Update: Partial<Database['public']['Tables']['datastreams']['Insert']> };
      telemetry: { Row: { id:number; device_id:string; datastream_id:string|null; value:number; recorded_at:string; metadata:Json }; Insert: { id?:number; device_id:string; datastream_id?:string|null; value:number; recorded_at?:string; metadata?:Json }; Update: Partial<Database['public']['Tables']['telemetry']['Insert']> };
      device_state: { Row: { device_id:string; state:Json; updated_at:string }; Insert: { device_id:string; state?:Json; updated_at?:string }; Update: Partial<Database['public']['Tables']['device_state']['Insert']> };
      device_commands: { Row: { id:string; device_id:string; command:string; payload:Json; status:string; created_at:string; sent_at:string|null; acknowledged_at:string|null }; Insert: { id?:string; device_id:string; command:string; payload?:Json; status?:string; created_at?:string; sent_at?:string|null; acknowledged_at?:string|null }; Update: Partial<Database['public']['Tables']['device_commands']['Insert']> };
      alert_rules: { Row: { id:string; project_id:string; device_id:string; datastream_id:string; name:string; operator:string; threshold:number; severity:string; cooldown_seconds:number; enabled:boolean; action:string; webhook_url:string|null; last_triggered_at:string|null; active:boolean; created_at:string }; Insert: { id?:string; project_id:string; device_id:string; datastream_id:string; name:string; operator:string; threshold:number; severity?:string; cooldown_seconds?:number; enabled?:boolean; action?:string; webhook_url?:string|null; last_triggered_at?:string|null; active?:boolean; created_at?:string }; Update: Partial<Database['public']['Tables']['alert_rules']['Insert']> };
      notifications: { Row: { id:string; user_id:string|null; project_id:string|null; kind:string; severity:string; title:string; message:string; read:boolean; device_id:string|null; datastream_id:string|null; source_id:string|null; created_at:string }; Insert: { id:string; user_id?:string|null; project_id?:string|null; kind:string; severity:string; title:string; message:string; read?:boolean; device_id?:string|null; datastream_id?:string|null; source_id?:string|null; created_at?:string }; Update: Partial<Database['public']['Tables']['notifications']['Insert']> };
      notification_subscriptions: { Row: { id:string; user_id:string; project_id:string|null; kind:string; severity:string; enabled:boolean; created_at:string }; Insert: { id?:string; user_id:string; project_id?:string|null; kind?:string; severity?:string; enabled?:boolean; created_at?:string }; Update: Partial<Database['public']['Tables']['notification_subscriptions']['Insert']> };
      notification_preferences: { Row: { preference_key:string; in_app:boolean; alert_notifications:boolean; webhook_notifications:boolean; critical_only:boolean; updated_at:string }; Insert: { preference_key:string; in_app?:boolean; alert_notifications?:boolean; webhook_notifications?:boolean; critical_only?:boolean; updated_at?:string }; Update: Partial<Database['public']['Tables']['notification_preferences']['Insert']> };
      device_claims: { Row: { id:string; device_id:string; claim_code:string; expires_at:string; claimed_at:string|null; created_at:string }; Insert: { id?:string; device_id:string; claim_code:string; expires_at:string; claimed_at?:string|null; created_at?:string }; Update: Partial<Database['public']['Tables']['device_claims']['Insert']> };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
